[profile.default]
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["Pasanaku"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config