name: CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run Foundry tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv

  # analyze:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
  #     - name: Run Slither
  #       uses: crytic/slither-action@v0.3.0
  #       with:
  #         node-version: 18
  #         fail-on: medium
  #         slither-args: --exclude-dependencies
